### ISSUE TITLE
Temperature of 1000+ from FT020T

### ISSUE THREAD

**Issue by benleavett** [switchdoclabs/rtl_433#1]
The temperature reading for my new unit doesn't seem right - it's consistently over 1000. 

I've looked in [the code](https://github.com/switchdoclabs/rtl_433/blob/445d1f3aad8ac48e15d839cf55b9fa562356e173/src/devices/switchdoclabs_FT020T.c) and I still can't work out how I should convert it into C/F. What does a temperature of 1077 mean in C/F? 

The raw data I get from my new unit and this [script from switchdoclabs](https://github.com/switchdoclabs/SDL_Pi_WeatherRack2/blob/master/readWeatherSensors.py):

{
"avewindspeed": 0,
"batterylow": 1,
"cumulativerain": 144,
"gustwindspeed": 0,
"humidity": 64,
"id": 0,
"light": 0,
"mic": "CRC",
"model": "SwitchDoc Labs-FT020T",
"temperature": 1077,
"time": "2020-11-18 18:45:16",
"uv": 0,
"winddirection": 0
}

**Comment by switchdoclabs** [comment]
The temperature comes from the FT020T in F with an offset.

Temperature F = (received temperature - 400)/10.0

We have a chart giving all the transforms.  We will add it to the README.md

SDL

**Comment by benleavett** [comment]
Thanks. I would love to see a table that explained all the units / transforms for each field.

**Comment by mwaterbu** [comment]
@switchdoclabs any reason not to just do the conversion in switchdoclabs_FT020T.c, as is done for switchdoclabs_F016TH.c?
I created a pull request (#2) that does this.
