### ISSUE TITLE
The new switchdoclabs_weathersenseWR3.c broke compilation

### ISSUE THREAD

**Issue by filipecustodio** [switchdoclabs/rtl_433#4]
Good morning,

The latest update (file switchdoclabs_weathersenseWR3.c) broke compilation:

[ 92%] Linking C executable rtl_433
/usr/bin/ld: CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseWR3.c.o:(.bss+0x44): multiple definition of `switchdoclabs_weathersenseRad_data_payload'; CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseRad.c.o:(.bss+0x44): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/rtl_433.dir/build.make:2460: src/rtl_433] Error 1
make[1]: *** [CMakeFiles/Makefile2:1029: src/CMakeFiles/rtl_433.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

The problem seems to be in line 19:
int switchdoclabs_weathersenseRad_data_payload[RH_ASK_MAX_MESSAGE_LEN];

This array is already defined, with the same name, in switchdoclabs_weathersenseRad.c.

Best regards,

Filipe Custódio

**Comment by switchdoclabs** [comment]
Fixed!  It was a typo.  Funny how it would compile on my system and break on yours.  Some caching going on I think.  I cleared it and rebuilt.

**Comment by filipecustodio** [comment]
Thank you! Have a great new year!

Cheers,

FC
