### ISSUE TITLE
Compiler issues building Switchdoc

### ISSUE THREAD

**Issue by owingst** [switchdoclabs/rtl_433#5]
I am trying to get a new sensor to work (wh 51) along with SwitchDoc Labs weatherrack2. When I get the latest build, I see compiler issues. Also this build does not work with Fine Offset wh51 sensor, although it does work with root build but not with switchdocs. How do I get a fix for these compiler issues that works with wh51 -R142? Thanks!

time      : 2023-02-16 11:09:16 model     : Fineoffset-WH51                        ID        : 0d431e Battery level: 1.222     Battery   : 1800 mV       Moisture  : 7 %           Transmission boost: 0     AD raw    : 97 Integrity : CRC

`
rtl_433/src/devices/switchdoclabs_solarmax.c: In function ‘convertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_solarmax.c:149:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  149 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_solarmax.c: In function ‘convertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_solarmax.c:174:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  174 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_solarmax.c: In function ‘convertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_solarmax.c:199:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  199 |       };
      |        ^
[ 88%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_SM23.c.o
[ 89%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseAQI.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c: In function ‘AQIconvertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c:149:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  149 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c: In function ‘AQIconvertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c:174:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  174 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c: In function ‘AQIconvertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c:197:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  197 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c: In function ‘AQIconvertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAQI.c:220:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  220 |       };
      |        ^
[ 89%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseTB.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c: In function ‘TBconvertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c:148:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  148 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c: In function ‘TBconvertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c:173:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  173 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c: In function ‘TBconvertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c:196:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  196 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c: In function ‘TBconvertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseTB.c:219:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  219 |       };
      |        ^
[ 90%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseAS.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c: In function ‘ASconvertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c:149:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  149 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c: In function ‘ASconvertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c:174:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  174 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c: In function ‘ASconvertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c:197:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  197 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c: In function ‘ASconvertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseAS.c:220:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  220 |       };
      |        ^
[ 90%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseRad.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c: In function ‘RadconvertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c:150:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  150 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c: In function ‘RadconvertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c:175:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  175 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c: In function ‘RadconvertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c:198:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  198 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c: In function ‘RadconvertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseRad.c:221:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  221 |       };
      |        ^
[ 91%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseWR3.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c: In function ‘WR3convertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c:150:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  150 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c: In function ‘WR3convertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c:175:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  175 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c: In function ‘WR3convertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c:198:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  198 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c: In function ‘WR3convertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3.c:221:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  221 |       };
      |        ^
[ 91%] Building C object src/CMakeFiles/rtl_433.dir/devices/switchdoclabs_weathersenseWR3PW.c.o
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c: In function ‘WR3PWconvertByteToLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c:150:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  150 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c: In function ‘WR3PWconvertByteToUnsignedLong’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c:175:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  175 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c: In function ‘WR3PWconvertByteToUnsignedInt’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c:198:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  198 |       };
      |        ^
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c: In function ‘WR3PWconvertByteToFloat’:
/home/pi/rtl_433/src/devices/switchdoclabs_weathersenseWR3PW.c:221:8: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
  221 |       };
      |        ^
`

**Comment by switchdoclabs** [comment]
I think all the above are warnings but it still works.  W get the same warnings when we compile it.

SDL
